### ISSUE TITLE
Scrape a lot of toml files to test the parser with

### ISSUE THREAD

**Issue by mackwic** [ocaml-toml/To.ml#18]
Maybe keep them in a different directory ?
The github api will not like it a lot, but hey, for science.

This is the tracking issue of the scraping work.

**Comment by sagotch** [comment]
If we do not want to pollute the `master` branch, we just could gather them in a `test` one. This is actually my preferred option.

**Comment by mackwic** [comment]
:+1: Or even in a different repository. It would become a language agnostic collection.

**Comment by sagotch** [comment]
Actually could even be better!

**Comment by zapashcanon** [comment]
Closing as it's the same as #19.
