### ISSUE TITLE
Generate a github page for the project and migrate the documentation on it

### ISSUE THREAD

**Issue by mackwic** [ocaml-toml/To.ml#20]
Tracking issue.
TODO: suggest some designs / screnshoot from the github templates / nice projects

**Comment by sagotch** [comment]
What do you call a github page? Is it the same as https://github.com/sagotch/To.ml/tree/gh-pages? (a `gh-pages` branch with some html files in it)

**Comment by mackwic** [comment]
Yes, partly. There is two sides to the github pages: the infrastructure, and the generation.
On the infra side, you did right (I didn't saw it, thought it was self hosted, my bad). But on the generation side, there is [a lot of pretty templates](https://github.com/blog/1081-instantly-beautiful-project-pages) from which we should integrate with or another template. It's a matter of html/css skills, not a big deal but still some work.

**Comment by zapashcanon** [comment]
They are now generated, so I'm closing. If someone wants to make them prettier, that's still possible.
