### ISSUE TITLE
Gather data on "who use Toml ?"

### ISSUE THREAD

**Issue by mackwic** [ocaml-toml/To.ml#24]
It seems that we already have some user. Find them, and feature them in the readme. Also, add a call to action in the Readme to be in the featured list.

**Comment by orbifx** [comment]
Used for configuring [Logarion](https://gitlab.com/orbifx/logarion/)'s configuration.

**Comment by zapashcanon** [comment]
Done in https://github.com/ocaml-toml/To.ml/commit/338bb92b2f79a7f29ef6c6eac0e40a8dd146a6c2 ; @ghost I wanted to add Logarion but couldn't find it on opam and th elink you provided is dead.
