### ISSUE TITLE
Use ppx_deriving for transparent toml serialisation

### ISSUE THREAD

**Issue by mackwic** [ocaml-toml/To.ml#25]
See: https://github.com/whitequark/ppx_deriving

We should not provide it in the main package (hide it behind a build flag) as some users don't want libraries to add unexpected syntax extension.

**Comment by sagotch** [comment]
:+1:

**Comment by zapashcanon** [comment]
Is it still useful as we have cconv support now ? @c-cube

**Comment by c-cube** [comment]
I have absolutely no idea.

**Comment by zapashcanon** [comment]
I'm not sure to get the idea. You could just store the string representation of your TOML datas or use `Marshal` ? I'm closing...
