### ISSUE TITLE
Inconsistent signature of TomlTypes.Table in v5.0.0

### ISSUE THREAD

**Issue by gersonmoraes** [ocaml-toml/To.ml#59]
Hi there,

There is a problem with the documentation for version `v5.0.0` - *it lies at least 10 times*. The problem is the signature of `TomlTypes.Table`, generated with the Stdlib's `Map.Make` that has changed many times since OCaml 4.02. Since there's not a `*.mli` file, the incompatibility is only noticed when you try to access the API. Below there's a list of functions from [`Map.S`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Map.S.html) (the result of `Map.Make`) and whey they were introduced:

Since 4.03.0
- union

Since 4.05.0:
- find_opt
- find_first
- find_last
- find_first_opt
- find_last_opt
- choose_opt
- max_binding_opt
- min_binding_opt

Since 4.06.0:
- update

**Comment by zapashcanon** [comment]
I bumped the minimal OCaml version to 4.07, so it isn't lying anymore except on  `filter_map` which was added in OCaml 4.11. That's good enough so I'm closing.
