### ISSUE TITLE
Consider using deprecation warnings before breaking the API

### ISSUE THREAD

**Issue by dmbaturin** [ocaml-toml/To.ml#68]
Whether renaming `TomlTypes` and `TomlLenses` to `Toml.Types` and `Toml.Lenses` was a good idea or not... for heavens sake, consider warning your users about that kind of stuff.

I see you've compiled a list of projects using your lib. You knew whose code you are breaking. What was it that kept you from making a 5.1.0 release with deprecation warnings to allow them to adjust dependencies of existing package versions to hardcode `toml <= 5.0.0`?

Hell, you knew it's a small list—you could _tell_ those people about your plans. And you chose to unexpectedly break it instead.

**Comment by zapashcanon** [comment]
I fixed the opam files of all project using the library in opam-repository, [including soupault](https://github.com/ocaml/opam-repository/pull/17835/files#diff-75dd7db5cc9b385f2e8960271956939ab2fc3744e8855b1999c175032f867788R25). If I understand correctly, you released the new soupault (3 days ago) just after the new toml was released (5 days ago), but as the two opam-repository PR were merged only 3 days ago, I didn't noticed and it wasn't catched by opam CI. If soupault was released one day later, it would have been catched by the CI.

Actually I was even about to make PR to all projects using the library but I was waiting for the new release to be available on opam. Indeed I could have done a release with deprecation warnings but didn't think about it, sorry.
