### ISSUE TITLE
Release compatible with menhir ≥ 20211215 (and newer dune?)

### ISSUE THREAD

**Issue by nberth** [ocaml-toml/To.ml#80]
It would appear the most recent version of `toml` available on opam is 7.0.0, but it requires somewhat oldish versions of menhir. Commit 41172b7 solves this, but there does not appear to have been any release since.

**Comment by nberth** [comment]
Just realizing the commit mentioned is a very small change. So this may actually just boil down to manually fix the spec. for 7.0.0 in the opam repo.

**Comment by nberth** [comment]
Now hitting errors with newer `dune` (cf https://github.com/ocaml/opam-repository/pull/22513).

**Comment by zapashcanon** [comment]
Fixed in #81.
